local M = {}

function M.setup(p, c)
	local bg = c.transparent and "NONE" or p.base03
	local bg_alt = c.transparent and "NONE" or p.base02
	local bg_soft = p.base02
	local fg = p.base0
	local fg_alt = p.base1
	local muted = p.base01

	return {
		Normal = { fg = fg, bg = bg },
		NormalNC = { fg = fg, bg = bg },
		NormalFloat = { fg = fg, bg = bg_alt },
		FloatBorder = { fg = muted, bg = bg_alt },
		FloatTitle = { fg = fg_alt, bg = bg_alt, bold = c.bold },
		ColorColumn = { bg = bg_soft },
		CursorLine = { bg = bg_soft },
		CursorColumn = { bg = bg_soft },
		CursorLineNr = { fg = p.yellow, bg = bg, bold = c.bold },
		LineNr = { fg = muted, bg = bg },
		SignColumn = { fg = fg, bg = bg },
		FoldColumn = { fg = muted, bg = bg },
		Folded = { fg = fg_alt, bg = bg_alt },
		EndOfBuffer = { fg = bg_soft, bg = bg },
		NonText = { fg = muted },
		Whitespace = { fg = bg_soft },
		VertSplit = { fg = muted, bg = bg },
		WinSeparator = { fg = muted, bg = bg },
		StatusLine = { fg = fg_alt, bg = bg_alt },
		StatusLineNC = { fg = muted, bg = bg_alt },
		TabLine = { fg = muted, bg = bg_alt },
		TabLineFill = { fg = muted, bg = bg_alt },
		TabLineSel = { fg = fg, bg = bg, bold = c.bold },
		WinBar = { fg = fg_alt, bg = bg },
		WinBarNC = { fg = muted, bg = bg },

		Pmenu = { fg = fg, bg = bg_alt },
		PmenuSel = { fg = fg_alt, bg = bg_soft, bold = c.bold },
		PmenuSbar = { bg = bg_alt },
		PmenuThumb = { bg = muted },

		Visual = { bg = bg_soft },
		Search = { fg = p.base03, bg = p.yellow },
		IncSearch = { fg = p.base03, bg = p.orange },
		CurSearch = { fg = p.base03, bg = p.orange, bold = c.bold },
		MatchParen = { fg = p.cyan, bg = bg_soft, bold = c.bold },

		Directory = { fg = p.blue },
		Title = { fg = p.yellow, bold = c.bold },
		Question = { fg = p.cyan, bold = c.bold },
		MoreMsg = { fg = p.cyan, bold = c.bold },
		ModeMsg = { fg = fg_alt, bold = c.bold },
		WarningMsg = { fg = p.orange, bold = c.bold },
		ErrorMsg = { fg = p.red, bold = c.bold },

		DiffAdd = { fg = p.green, bg = bg_soft },
		DiffChange = { fg = p.yellow, bg = bg_soft },
		DiffDelete = { fg = p.red, bg = bg_soft },
		DiffText = { fg = p.blue, bg = bg_soft, bold = c.bold },

		SpellBad = { sp = p.red, undercurl = c.undercurl },
		SpellCap = { sp = p.yellow, undercurl = c.undercurl },
		SpellLocal = { sp = p.cyan, undercurl = c.undercurl },
		SpellRare = { sp = p.magenta, undercurl = c.undercurl },

		Comment = { fg = muted, italic = c.italic },
		Constant = { fg = p.orange },
		String = { fg = p.cyan },
		Character = { fg = p.cyan },
		Number = { fg = p.violet },
		Boolean = { fg = p.violet },
		Float = { fg = p.violet },
		Identifier = { fg = fg },
		Function = { fg = p.blue },
		Statement = { fg = p.green },
		Conditional = { fg = p.green },
		Repeat = { fg = p.green },
		Label = { fg = p.yellow },
		Operator = { fg = fg_alt },
		Keyword = { fg = p.green },
		Exception = { fg = p.orange },
		PreProc = { fg = p.orange },
		Include = { fg = p.yellow },
		Define = { fg = p.orange },
		Macro = { fg = p.orange },
		PreCondit = { fg = p.orange },
		Type = { fg = p.yellow },
		StorageClass = { fg = p.yellow },
		Structure = { fg = p.yellow },
		Typedef = { fg = p.yellow },
		Special = { fg = p.orange },
		SpecialChar = { fg = p.red },
		Tag = { fg = p.blue },
		Delimiter = { fg = fg_alt },
		SpecialComment = { fg = muted, italic = c.italic },
		Debug = { fg = p.red },
		Underlined = { fg = p.blue, underline = c.underline },
		Ignore = { fg = muted },
		Error = { fg = p.red },
		Todo = { fg = p.magenta, bg = bg_soft, bold = c.bold },

		DiagnosticError = { fg = p.red },
		DiagnosticWarn = { fg = p.yellow },
		DiagnosticInfo = { fg = p.blue },
		DiagnosticHint = { fg = p.cyan },
		DiagnosticOk = { fg = p.green },
		DiagnosticVirtualTextError = { fg = p.red, bg = bg_alt },
		DiagnosticVirtualTextWarn = { fg = p.yellow, bg = bg_alt },
		DiagnosticVirtualTextInfo = { fg = p.blue, bg = bg_alt },
		DiagnosticVirtualTextHint = { fg = p.cyan, bg = bg_alt },
		DiagnosticUnderlineError = { sp = p.red, undercurl = c.undercurl },
		DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = c.undercurl },
		DiagnosticUnderlineInfo = { sp = p.blue, undercurl = c.undercurl },
		DiagnosticUnderlineHint = { sp = p.cyan, undercurl = c.undercurl },
		DiagnosticFloatingError = { fg = p.red },
		DiagnosticFloatingWarn = { fg = p.yellow },
		DiagnosticFloatingInfo = { fg = p.blue },
		DiagnosticFloatingHint = { fg = p.cyan },

		LspReferenceText = { bg = bg_soft },
		LspReferenceRead = { bg = bg_soft },
		LspReferenceWrite = { bg = bg_soft },

		GitSignsAdd = { fg = p.green },
		GitSignsChange = { fg = p.yellow },
		GitSignsDelete = { fg = p.red },

		BufferLineFill = { fg = muted, bg = bg_alt },
		BufferLineBackground = { fg = muted, bg = bg_alt },
		BufferLineBufferVisible = { fg = fg_alt, bg = bg_alt },
		BufferLineBufferSelected = { fg = fg, bg = bg, bold = c.bold },
		BufferLineTab = { fg = muted, bg = bg_alt },
		BufferLineTabSelected = { fg = fg, bg = bg, bold = c.bold },
		BufferLineTabClose = { fg = muted, bg = bg_alt },
		BufferLineCloseButton = { fg = muted, bg = bg_alt },
		BufferLineCloseButtonVisible = { fg = fg_alt, bg = bg_alt },
		BufferLineCloseButtonSelected = { fg = p.red, bg = bg, bold = c.bold },
		BufferLineModified = { fg = p.yellow, bg = bg_alt },
		BufferLineModifiedVisible = { fg = p.yellow, bg = bg_alt },
		BufferLineModifiedSelected = { fg = p.yellow, bg = bg, bold = c.bold },
		BufferLineIndicatorSelected = { fg = p.blue, bg = bg },
		BufferLineIndicatorVisible = { fg = p.blue, bg = bg_alt },
		BufferLineIndicator = { fg = p.blue, bg = bg_alt },
		BufferLineSeparator = { fg = bg_alt, bg = bg_alt },
		BufferLineSeparatorVisible = { fg = bg_alt, bg = bg_alt },
		BufferLineSeparatorSelected = { fg = bg, bg = bg },
		BufferLineOffsetSeparator = { fg = bg_alt, bg = bg_alt },
		BufferLineDevIconDefault = { fg = p.blue, bg = bg_alt },
		BufferLineDevIconDefaultVisible = { fg = p.blue, bg = bg_alt },
		BufferLineDevIconDefaultSelected = { fg = p.blue, bg = bg, bold = c.bold },
		BufferLineDevIconDefaultInactive = { fg = muted, bg = bg_alt },
		BufferLineDevIcon = { fg = p.blue, bg = bg_alt },
		BufferLineDevIconVisible = { fg = p.blue, bg = bg_alt },
		BufferLineDevIconSelected = { fg = p.blue, bg = bg, bold = c.bold },
		BufferLineDevIconInactive = { fg = muted, bg = bg_alt },

		-- Plugin: indent-blankline
		-- IndentBlanklineChar = { fg = colors.fg_whitespace },
		-- IndentBlanklineContextChar = { fg = colors.purple },
		-- IndentBlanklineSpaceChar = { fg = colors.fg_whitespace },
		IblIndent = { fg = p.base0 },
		-- IblScope = { fg = colors.purple },

		["@comment"] = { fg = muted, italic = c.italic },
		["@comment.todo"] = { fg = p.magenta, bold = c.bold },
		["@constant"] = { fg = p.orange },
		["@constant.builtin"] = { fg = p.yellow, italic = c.italic },
		["@string"] = { fg = p.cyan },
		["@string.escape"] = { fg = p.red },
		["@string.special"] = { fg = p.yellow },
		["@character"] = { fg = p.cyan },
		["@number"] = { fg = p.violet },
		["@boolean"] = { fg = p.violet },
		["@float"] = { fg = p.violet },
		["@function"] = { fg = p.blue },
		["@function.builtin"] = { fg = p.blue, italic = c.italic },
		["@function.call"] = { fg = p.blue },
		["@method"] = { fg = p.blue },
		["@method.call"] = { fg = p.blue },
		["@keyword"] = { fg = p.green },
		["@keyword.function"] = { fg = p.green },
		["@keyword.operator"] = { fg = p.orange },
		["@keyword.return"] = { fg = p.green },
		["@conditional"] = { fg = p.green },
		["@repeat"] = { fg = p.green },
		["@operator"] = { fg = fg_alt },
		["@type"] = { fg = p.yellow },
		["@type.builtin"] = { fg = p.yellow, italic = c.italic },
		["@type.definition"] = { fg = p.yellow },
		["@type.qualifier"] = { fg = p.yellow },
		["@attribute"] = { fg = p.yellow },
		["@property"] = { fg = p.yellow },
		["@field"] = { fg = fg },
		["@parameter"] = { fg = fg },
		["@variable"] = { fg = fg },
		["@variable.builtin"] = { fg = p.yellow, italic = c.italic },
		["@namespace"] = { fg = p.blue },
		["@module"] = { fg = p.blue },
		["@constructor"] = { fg = p.blue },
		["@punctuation"] = { fg = fg_alt },
		["@punctuation.delimiter"] = { fg = fg_alt },
		["@punctuation.bracket"] = { fg = fg_alt },
		["@tag"] = { fg = p.blue },
		["@tag.builtin"] = { fg = p.blue },
		["@tag.attribute"] = { fg = p.yellow },
		["@tag.delimiter"] = { fg = fg_alt },
		["@label"] = { fg = p.yellow },

		["@text"] = { fg = fg },
		["@text.title"] = { fg = p.yellow, bold = c.bold },
		["@text.strong"] = { bold = c.bold },
		["@text.emphasis"] = { italic = c.italic },
		["@text.uri"] = { fg = p.blue, underline = c.underline },

		["@markup.heading"] = { fg = p.yellow, bold = c.bold },
		["@markup.strong"] = { bold = c.bold },
		["@markup.italic"] = { italic = c.italic },
		["@markup.link"] = { fg = p.blue, underline = c.underline },
		["@markup.raw"] = { fg = p.cyan },

		["@diff.plus"] = { fg = p.green },
		["@diff.minus"] = { fg = p.red },
		["@diff.delta"] = { fg = p.yellow },

		["@lsp.typemod.variable.defaultLibrary.typescript"] = { fg = p.yellow },
		["@lsp.typemod.variable.defaultLibrary"] = { fg = p.yellow },
		["@lsp.typemod.method.defaultLibrary.typescript"] = { fg = p.blue },

		TSTag = { fg = p.blue },
		TSTagDelimiter = { fg = fg_alt },
		TSTagAttribute = { fg = p.yellow },
	}
end

return M
